spring:
  redis:
    host: 127.0.0.1
    port: 6380
    password: 123456
    database: 6
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  rabbitmq:
    username: guest
    password: 123456
    host: localhost
  cloud:
    gateway:
      routes:
      - id: auth-service_route
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/auth-service/**
        filters:
        - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@hostAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
      - id: config-server_route
        uri: lb://CONFIG-SERVER
        predicates:
        - Path=/config-server/**
        filters:
        - RewritePath=/config-server/(?<segment>.*), /$\{segment}
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@hostAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
      - id: user-server_route
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user-service/**
        filters:
        - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@hostAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
      - id: demo-server_route
        uri: lb://DEMO-SERVICE
        predicates:
        - Path=/demo-service/**
        filters:
        - RewritePath=/demo-service/(?<segment>.*), /$\{segment}
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@hostAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20

security:
  oauth2:
    client:
      grant-type: client_credentials
      access-token-uri: http://localhost:9130/auth-service/oauth/token
      user-authorization-uri: http://localhost:9130/auth-service/oauth/authorize
      client-id: gateway-server
      client-secret: gateway-server_password
    resource:
      user-info-uri: http://localhost:9130/auth-service/users/current