server:
  port: 9100

eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://registry2:123456@peer2:9101/eureka/

spring:
  security:
    user:
      name: registry1
      password: 123456