server:
  port: 9100

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  security:
    user:
      name: registry
      password: 123456