server:
  port: 9101

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://registry1:123456@peer1:9100/eureka/

spring:
  security:
    user:
      name: registry2
      password: 123456